import { NavbarDemo } from "@/components/NavbarDemo";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function Layout({
  children,
  profile,
  ai_profile,
}: Readonly<{
  children: React.ReactNode
  profile: React.ReactNode
  ai_profile: React.ReactNode
}>)
{
    return (
        <>
    <div className="hidden sm:block">
      <NavbarDemo/>
      </div>
      <div className="flex">
        {children}
        {profile}
        {ai_profile}
      </div>
      </>
    )
  }