import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {NavbarDemo} from "../components/NavbarDemo";
import Index from "../components/Header/Index";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="hidden sm:block">
      <NavbarDemo/>
      </div>
      <div className="block sm:hidden">
        <Index/>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
